package com.softdesign.devintensive2.utils;

public interface ConstantManager {
    String TAG_PREFIX = "DEV ";
    String COLOR_MODE_KEY = "COLOR_MODE_KEY";

    String EDIT_MODE_KEY = "EDIT_MODE_KEY";

    String USER_PHONE_KEY = "USER_PHONE_KEY";
    String USER_EMAIL_KEY = "USER_EMAIL_KEY";
    String USER_FACEBOOK_KEY = "USER_FACEBOOK_KEY";
    String USER_GITHUB_KEY = "USER_GITHUB_KEY";
    String USER_ABOUT_KEY = "USER_ABOUT_KEY";
    String USER_PHOTO_KEY = "USER_PHOTO_KEY";
    String AUTH_TOKEN = "AUTH_TOKEN";
    String USER_ID_KEY = "USER_ID_KEY";
    String USER_RATING_VALUE = "USER_RATING_VALUE";
    String USER_CODE_LINES_VALUE = "USER_CODE_LINES_VALUE";
    String USER_PROJECT_VALUE = "USER_PROJECT_VALUE";
    String PARCELABLE_KEY = "PARCELABLE_KEY";


    int LOAD_PROFILE_PHOTO = 0;
    int REQUEST_CAMERA_PICTURE = 99;
    int REQUEST_GALLERY_PICTURE = 98;
    int PERMISSION_REQUEST_SETTINGS_CODE = 97;
    int CAMERA_REQUEST_PERMISSION_CODE = 98;
}
