package com.softdesign.devintensive2.utils;

public interface ConstantManager {
    String TAG_PREFIX = "DEV_";
    String COLOR_MODE_KEY = "COLOR_MODE_KEY";

    String EDIT_MODE_KEY = "EDIT_MODE_KEY";

    String USER_PHONE_KEY = "USER_PHONE_KEY";
    String USER_EMAIL_KEY = "USER_EMAIL_KEY";
    String USER_FACEBOOK_KEY = "USER_FACEBOOK_KEY";
    String USER_GITHUB_KEY = "USER_GITHUB_KEY";
    String USER_ABOUT_KEY = "USER_ABOUT_KEY";

    int LOAD_PROFILE_PHOTO = 0;

    int REQUEST_CAMERA_PICTURE = 99;
    int REQUEST_GALLERY_PICTURE = 98;
    String USER_PHOTO_KEY = "USER_PHOTO_KEY";
    int PERMISSION_REQUEST_SETTINGS_CODE = 97;
    int CAMERA_REQUEST_PERMISSION_CODE = 98;
//    int LOAD_PROFILE_CAMERA = 1;
//    int CANCEL_PROFILE_DIALOG = 2;
}
